### ISSUE TITLE
Installation tutorial - add info on how to choose pyside/pyqt backends

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/tutorials#50]
It would be good to include information in the installation tutorial about choosing different backends for napari (pyside2/pyqt5).

There is an open issue at  https://github.com/napari/napari/issues/704 which discusses how we should use pip extras for this. The leading current suggestion is this https://github.com/napari/napari/issues/704#issuecomment-555361517:
> `pip install napari` -> get PySide2
> `pip install napari[pyqt]` or `pip install napari[pyqt5]` -> get PyQt5
> `pip install napari[pyside]` or `pip install napari[pyside2]` -> get PySide2

When this is settled in the main napari repository, I'd suggest adding a short section on choosing different backends, maybe just before the section on troubleshooting in `napari-tutorials/tutorials/installation.md`.

**Comment by sumanthratna** [comment]
I think you guys can close this now :)

https://napari.org/#installation does a good job of explaining the backends.
