### ISSUE TITLE
napari + imageJ  integration how-to-guide

### ISSUE THREAD

**Issue by sofroniewn** [napari/tutorials#57]
It would be great to adapt the demos on napari + imageJ integration [here](https://forum.image.sc/t/read-images-with-imagej-display-them-with-napari/32156) and [here](https://forum.image.sc/t/displaying-imagej-and-napari-ui-simultaneously/32187) by @ctrueden into a how-to-guide, similar to the [dask + napari how to guide](https://github.com/napari/tutorials/blob/master/applications/dask.md)

**Comment by wokira** [comment]
I adapted these demos in a how-to-guide. Please find and review my contribution in PR #69 .

**Comment by wokira** [comment]
[How-to-Guide for integrating ImageJ and Napari](https://github.com/napari/tutorials/pull/69)

**Comment by wokira** [comment]
[How-go-guide for integrating ImageJ+napari](https://github.com/napari/tutorials/pull/69)

**Comment by wokira** [comment]
#69

**Comment by jni** [comment]
Fixed by #69. Thank you @wokira!
