### ISSUE TITLE
Hyperlink doesn't work

### ISSUE THREAD

**Issue by Mishrasubha** [napari/tutorials#58]
So, I was browsing through your website napari.org/tutorials and I saw the urls for getting started section do not work.  It is not a major issue and the links at the bottom of the page under fundamentals work but I just wanted to let you know.

**Comment by Mishrasubha** [comment]
![upload napari](https://user-images.githubusercontent.com/32950636/77048586-b64e3b00-69ec-11ea-96c5-140f34b89246.PNG)
  This is the section where the hyperlinks do not work.

**Comment by Mishrasubha** [comment]
Please review my pull requests.

**Comment by sofroniewn** [comment]
Thanks so much for making those PRs!! #59 and #60, we'll get them both in promptly :-)
