### ISSUE TITLE
Semantic line breaks in docs

### ISSUE THREAD

**Issue by hectormz** [napari/tutorials#78]
I was looking through the tutorial files after running `codespell` in the main repo.

I think it could be easier to maintain/view the markdown files if semantic line breaks were used (new lines after period or comma etc). Currently each "paragraph" is on a single line. The output would be the same.

This will make it easier to identify the changes in a given commit since the lines are much shorter.

### Ex:
```
The input data to the vectors layer must either be a Nx2xD numpy array representing N vectors with start position and projection values in D dimensions, or it must be an N1xN2 ... xNDxD, array where each of the first D dimensions corresponds to the voxel of the location of the vector, and the last dimension contains the D values of the projection of that vector. The former representation is useful when you have vectors that can start in arbitrary positions in the canvas. The latter representation is useful when your vectors are defined on a grid, say corresponding to the voxels of an image, and you have one vector per grid.
```
could be
```
The input data to the vectors layer must either be a Nx2xD numpy array representing N vectors with start position and projection values in D dimensions,
or it must be an N1xN2 ... xNDxD, array where each of the first D dimensions corresponds to the voxel of the location of the vector,
and the last dimension contains the D values of the projection of that vector.
The former representation is useful when you have vectors that can start in arbitrary positions in the canvas.
The latter representation is useful when your vectors are defined on a grid,
say corresponding to the voxels of an image, and you have one vector per grid.
```
which still renders the same.

There's room for debate for some of the linebreaks, but it could overall be helpful

**Comment by tlambert03** [comment]
this would make me super happy, and I've had to reformat a lot of .md docs in the main repo like this as well.
I would go even farther and suggest that we add full-on `markdownlint` somewhere in the toolchain.  The question is "where" ... since we definitely want to keep the tutorials _particularly_ easy to contribute to, so is it ok to expect a contributor to setup pre-commit locally to run markdownlint?

**Comment by hectormz** [comment]
Are you referring specifically to https://github.com/markdownlint/markdownlint ? Do you have experience with it?

I think it might be a lot to ask someone to setup `pre-commit` if they're only contributing to the tutorials. 

CI is an option, but it's frustrating to have to push changes in a PR in order to get feedback.
In addition to CI, you could suggest/request contributors run it locally, and maybe setup with a `make` file that runs similar checks before making a PR. Not sure if it's more reasonable for someone to setup `make` over `pre-commit`.
I overall appreciate `pre-commit` and what it achieves, but it can be frustrating on projects with multiple/slow hooks.

**Comment by tlambert03** [comment]
> Are you referring specifically to https://github.com/markdownlint/markdownlint ? Do you have experience with it?

yep that's the one.  I use it as a linter in VScode, but I don't run it locally or in CI anywhere.

It's fine to kick this can down the road... in the meantime, I would (personally) fully support a PR that changes all of our massive one-liners to line-length-limited docs.

**Comment by jni** [comment]
I very much like semantic breaks in markdown. That's what we used for Elegant SciPy, though we didn't have a linter so don't hold me to it. =P So another 👍 from me!

**Comment by hectormz** [comment]
Great! I can put a PR together for consideration. I've also been looking at making markdownlint happy, and fixing typos with codespell. I can put those three changes in three commits, or let me know if you want three separate PRs.

**Comment by jni** [comment]
We don't always squash in this repo (I think), so 3 commits is good.

**Comment by hectormz** [comment]
Okay good to know. I've noticed some inconsistencies in the docs, mostly about how napari is printed in plain text. I see it as **napari** as well as `napari` (or plain). Is that a purposeful distinction based on context, or they should all be one or the other?

**Comment by jni** [comment]
I think just napari (no fancy formatting). `napari` (monospace) should be reserved for the terminal command context.

**Comment by hectormz** [comment]
Okay, so I pulled in some examples from the tutorials. I didn't really see much usage in free text that should be monospace `napari`. But all these should be plain napari?

> **napari** can be easily coupled to leading machine learning and image analysis tools (e.g. `scikit-image`, `scikit-learn`, `TensorFlow`, `PyTorch`), enabling more user-friendly automated analysis.

> Calling `napari.view_image` will return a `Viewer` object that is the main object inside **napari**.

> To launch napari from a python script, inside your script you should import `napari`, create a Qt GUI context, and then create the `Viewer` by adding some data.

> And while `napari` can easily handle something like a `zarr` store, it can be a bit more limiting inasmuch as it requires programs that are capable of viewing it

> Now that you've got napari installed, checkout our [getting started](./getting_started) tutorial to start learning how to use it!

I think the monospace usage here could be warranted:

> We're a community partner on the [imagesc forum](https://forum.image.sc/tags/napari) and all usage support requests should be posted on the forum with the tag `napari`.
