### ISSUE TITLE
purge git history

### ISSUE THREAD

**Issue by ziyangczi** [napari/tutorials#96]
Right now the git is taking around 600M to track history, checking out the code is quite slow, we should try to clean up some of the histories to speed it up

**Comment by jni** [comment]
Why did you close this @ziyangczi? Did you discover `--clone-depth`? :joy: I still think it's a good idea, the default option is to clone the whole history. But perhaps the right time to purge is after #95 goes in and all the examples become auto-generated, which would allow us to remove all our screenshots/gifs. And btw we should not use gifs, they are terrible for space efficiency.

**Comment by ziyangczi** [comment]
I later realized that those gif files also takes another 300M, so the git is more or less irrelevant, but once we are able to automate the generation, we certainly want to clean up the git history to speed up checkout
